/**
 * Builds src/words/allowlist.ts and src/words/targets.ts.
 *
 * Sources (see LICENSES.md):
 *   - ENABLE (enable1.txt), public domain: scripts/data/enable1.txt
 *   - SCOWL via the `wordlist-english` npm package (Kevin Atkinson, permissive notice)
 *
 * No NYT / Wordle lists are used, directly or indirectly.
 *
 *   allowlist = ENABLE 5-letter words ∪ SCOWL (size ≤ 50) 5-letter lowercase words
 *   targets   = ENABLE ∩ SCOWL (size ≤ 35), minus plurals / -ed forms of common
 *               shorter words, minus the blocklist below
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const require = createRequire(import.meta.url)

const isWord = (w: string) => /^[a-z]+$/.test(w)

function scowl(sizes: number[]): Set<string> {
  const out = new Set<string>()
  for (const dialect of ['english', 'american']) {
    for (const size of sizes) {
      const words: string[] = require(`wordlist-english/${dialect}-words-${size}.json`)
      for (const w of words) if (isWord(w)) out.add(w)
    }
  }
  return out
}

const enable = readFileSync(join(here, 'data/enable1.txt'), 'utf8')
  .split(/\r?\n/)
  .map((w) => w.trim())
  .filter(isWord)

const enableSet = new Set(enable)
const enable5 = enable.filter((w) => w.length === 5)
const common = scowl([10, 20, 35])
const broad = scowl([10, 20, 35, 40, 50])

// Offensive or crude words that should never be a target. They stay guessable if
// they are in the allowlist; this only keeps them from being dealt as answers.
const BLOCKLIST = new Set([
  'bitch', 'boobs', 'dicks', 'dildo', 'dykes', 'farts', 'fucks', 'hussy', 'nazis',
  'negro', 'porno', 'prick', 'pussy', 'queer', 'semen', 'shits', 'slags', 'sluts',
  'spics', 'titty', 'turds', 'twats', 'whore', 'wench', 'rapes', 'raped', 'sexed',
  'sexes', 'lynch', 'gonad', 'horny', 'kinky', 'pubic', 'sperm', 'moron',
])

const isCommonShorter = (stem: string) => stem.length >= 3 && common.has(stem) && enableSet.has(stem)

function isInflection(w: string): boolean {
  // plural / 3rd person of a common 4-letter word: CATS, BAKES
  if (w.endsWith('s') && !w.endsWith('ss') && isCommonShorter(w.slice(0, -1))) return true
  // BOXES, WISHES style: 3-letter stem + es
  if (w.endsWith('es') && isCommonShorter(w.slice(0, -2)) && /(s|x|z|ch|sh)$/.test(w.slice(0, -2))) return true
  // BAKED (bake + d), AIMED (aim + ed)
  if (w.endsWith('ed') && (isCommonShorter(w.slice(0, -1)) || isCommonShorter(w.slice(0, -2)))) return true
  return false
}

const allow = new Set<string>(enable5)
for (const w of broad) if (w.length === 5) allow.add(w)

const targets = enable5
  .filter((w) => common.has(w))
  .filter((w) => !isInflection(w))
  .filter((w) => !BLOCKLIST.has(w))
  .sort()

for (const t of targets) if (!allow.has(t)) throw new Error(`target not in allowlist: ${t}`)

const allowSorted = [...allow].sort()

function emit(file: string, name: string, words: string[], note: string) {
  // Stored as one packed string (5 chars per word) to keep the bundle small.
  const packed = words.join('')
  const body =
    `// GENERATED by scripts/build-wordlists.ts — do not edit by hand.\n` +
    `// ${note}\n` +
    `// ${words.length} words.\n` +
    `export const ${name} = '${packed}'\n`
  const path = join(root, 'src/words', file)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, body)
}

emit('allowlist.ts', 'ALLOWLIST_PACKED', allowSorted, 'Valid guesses: ENABLE ∪ SCOWL≤50 (5 letters).')
emit('targets.ts', 'TARGETS_PACKED', targets, 'Answers: ENABLE ∩ SCOWL≤35, inflections and blocklist removed.')

console.log(`allowlist: ${allowSorted.length}  targets: ${targets.length}`)
